ci: Introduce a negative test for ref override

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -274,6 +274,13 @@ jobs:
           ostree commit --repo=repo --canonical-permissions --branch=screenshots/${{ env.FP_ARCH }} builddir/files/share/app-info/media
           ostree refs --repo=repo
           flatpak run --command=flatpak-builder-lint org.flatpak.Builder//localtest --exceptions --ref app/org.flathub.gui/${{ env.FP_ARCH }}/master repo repo
+          output=$(flatpak run --command=flatpak-builder-lint org.flatpak.Builder//localtest --exceptions repo repo | jq -r '.errors[] | select(. == "desktop-file-exec-key-absent")')
+          if [ "$output" = "desktop-file-exec-key-absent" ]; then
+            echo "PASS"
+          else
+            echo "FAIL: $output"
+            exit 1
+          fi
 
   docker-call:
     permissions:
